estimated position unreliable if vision jumps position like crazy
Team488/TeamXbot2023 pull request #163
Opened 2023-04-01 21:52 UTC by sw990

compares previous and current estimated position

2023-04-02 16:35 UTC, aschokking requested changes

2023-04-02 16:35 UTC, aschokking commented on src/main/java/competition/subsystems/vision/VisionSubsystem.java
> +        double currentVector = previousEstimatedPose.getTranslation().getDistance(estimatedPose.estimatedPose.toPose2d().getTranslation());
at this point it's a distance (scalar single number) not a vector right?

2023-04-02 16:35 UTC, aschokking commented on src/main/java/competition/subsystems/vision/VisionSubsystem.java
> +    public boolean isEstimatedPoseReliable(EstimatedRobotPose estimatedPose, Pose2d previousEstimatedPose) {
there's a unit test on this method you'll need to update for this change (that's why the build is failing):
> D:\a\1\s\src\test\java\competition\subsystems\vision\VisionSubsystemTest.java:22: error: method isEstimatedPoseReliable in class VisionSubsystem cannot be applied to given types;
        assertFalse(subsystem.isEstimatedPoseReliable(new EstimatedRobotPose(

2023-04-05 03:19 UTC, stephenjust approved these changes

2023-04-05 14:59 UTC, aschokking approved these changes

2023-04-06 05:44 UTC, merged